#!/usr/bin/env bash
cd ..

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world-vanilla ]; then
    s3cmd sync world-vanilla/ s3://${AWS_BUCKET}/world/
  else
    mkdir -p world-vanilla
    cd world-vanilla
    s3cmd get --recursive s3://${AWS_BUCKET}/world/
    cd ..
  fi
  rm .s3cfg
fi
