#!/usr/bin/env bash
cd ..
echo "NDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH"
if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world-vanilla ]; then
  echo "Started sync..."
    s3cmd sync world-vanilla/ s3://${AWS_BUCKET}/world-vanilla/
  else
    echo "The directory does not exist. It will be created and get updated with the content inside the s3 bucket"
    mkdir -p world-vanilla
    cd world-vanilla
    s3cmd get --recursive s3://${AWS_BUCKET}/world-vanilla/
    cd ..
  fi
  rm .s3cfg
fi
