#!/usr/bin/env bash

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world-vanilla ]; then
    s3cmd sync world/ s3://${AWS_BUCKET}/world-vanilla/
  else
    mkdir -p world-vanilla
    cd world
    s3cmd get --recursive s3://${AWS_BUCKET}/world-vanilla/
    cd ..
  fi
  rm .s3cfg
fi
